package com.tradet.tradetservidor.hibernate;
// Generated 08-abr-2020 12:45:27 by Hibernate Tools 4.3.1


import java.util.HashMap;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sorteo generated by hbm2java
 */
@Entity
@Table(name="sorteo"
    ,catalog="tradet"
)
public class Sorteo  implements java.io.Serializable {


    private Integer sorteoId;
    private String nombre;
    private String descripcion;

    public Sorteo() {
    }

    public Sorteo(Integer sorteoId) {
        this.sorteoId = sorteoId;
    }
    
    

    public Sorteo(String nombre, String descripcion) {
       this.nombre = nombre;
       this.descripcion = descripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SORTEO_ID", unique=true)
    public Integer getSorteoId() {
        return this.sorteoId;
    }
    
    public void setSorteoId(Integer sorteoId) {
        this.sorteoId = sorteoId;
    }

    
    @Column(name="NOMBRE", length=20)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="DESCRIPCION", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Sorteo(HashMap map){
        if(map.containsKey("id"))
            sorteoId = (Integer) map.get("id");
        else
            sorteoId = null;
        nombre = (String) map.get("nombre");
        descripcion = (String) map.get("descripcion");
    }

    public HashMap toHash(){
        HashMap map = new HashMap();
        map.put("id", sorteoId);
        map.put("nombre", nombre);
        map.put("descripcion", descripcion);
        return map;
    }

}


