package com.tradet.tradetservidor.hibernate;
// Generated 08-abr-2020 12:45:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ValoracionId generated by hbm2java
 */
@Embeddable
public class ValoracionId  implements java.io.Serializable {


     private int usuarioValoradoId;
     private int usuarioValoradorId;

    public ValoracionId() {
    }

    public ValoracionId(int usuarioValoradoId, int usuarioValoradorId) {
       this.usuarioValoradoId = usuarioValoradoId;
       this.usuarioValoradorId = usuarioValoradorId;
    }
   


    @Column(name="USUARIO_VALORADO_ID", nullable=false)
    public int getUsuarioValoradoId() {
        return this.usuarioValoradoId;
    }
    
    public void setUsuarioValoradoId(int usuarioValoradoId) {
        this.usuarioValoradoId = usuarioValoradoId;
    }


    @Column(name="USUARIO_VALORADOR_ID", nullable=false)
    public int getUsuarioValoradorId() {
        return this.usuarioValoradorId;
    }
    
    public void setUsuarioValoradorId(int usuarioValoradorId) {
        this.usuarioValoradorId = usuarioValoradorId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ValoracionId) ) return false;
		 ValoracionId castOther = ( ValoracionId ) other; 
         
		 return (this.getUsuarioValoradoId()==castOther.getUsuarioValoradoId())
 && (this.getUsuarioValoradorId()==castOther.getUsuarioValoradorId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioValoradoId();
         result = 37 * result + this.getUsuarioValoradorId();
         return result;
   }   


}


